version: "3"
services:

    database:
      image: mysql:5.7
      container_name: api-database
      volumes:
        - data:/var/lib/mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=5ZSufRefgMFpJCH
        - MYSQL_DATABASE=api
        - MYSQL_USER=api
        - MYSQL_PASSWORD=w2gqZIUNjap
      ports:
        - "3306:3306"

    app:
      build:
        context: ./
      image: hub.gostartkit.com/api
      container_name: api-app
      depends_on:
        - database
      working_dir: /app
      volumes:
          - .:/app
      restart: always

    web:
      image: nginx:alpine
      container_name: api-web
      depends_on:
        - app
      working_dir: /app
      volumes:
          - .:/app
          - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      restart: always
      ports:
       - "80:80"

volumes:
  data: